### ISSUE TITLE
ReferenceError: IpynbView is not defined

### ISSUE THREAD

**Issue by umer7** [rgbkrk/language-ipynb#5]
I want to open .ipynb file in atom and i install this but this is giving me this error.(or is there any other way to open .ipynb files)

```
ReferenceError: IpynbView is not defined
    at Object.activate (file:///C:/Users/idcpt1212/.atom/packages/ipynb/lib/ipynb.coffee:5:22)
    at Package.activateNow (C:\Users\idcpt1212\AppData\Local\atom\app-1.30.0\resources\app\src\package.js:230:33)
    at measure (C:\Users\idcpt1212\AppData\Local\atom\app-1.30.0\resources\app\src\package.js:206:33)
    at Package.measure (C:\Users\idcpt1212\AppData\Local\atom\app-1.30.0\resources\app\src\package.js:88:25)
    at activationPromise.Promise (C:\Users\idcpt1212\AppData\Local\atom\app-1.30.0\resources\app\src\package.js:200:20)
    at new Promise (<anonymous>)
    at Package.activate (C:\Users\idcpt1212\AppData\Local\atom\app-1.30.0\resources\app\src\package.js:198:38)
    at PackageManager.activatePackage (C:\Users\idcpt1212\AppData\Local\atom\app-1.30.0\resources\app\src\package-manager.js:695:42)
    at C:\Users\idcpt1212\AppData\Local\atom\app-1.30.0\resources\app\node_modules\settings-view\lib\package-manager.js:491:35
    at exit (C:\Users\idcpt1212\AppData\Local\atom\app-1.30.0\resources\app\node_modules\settings-view\lib\package-manager.js:128:22)
    at triggerExitCallback (C:\Users\idcpt1212\AppData\Local\atom\app-1.30.0\resources\app\src\buffered-process.js:267:15)
    at ChildProcess.process.on (C:\Users\idcpt1212\AppData\Local\atom\app-1.30.0\resources\app\src\buffered-process.js:297:15)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
```

**Comment by rgbkrk** [comment]
I haven't touched / used this in a while. This would be worth having a contributor like yourself figuring out the current API via the [atom docs](https://atom.io/docs).
